name: CICD

on:
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code clone from Github"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
        run: echo "Docker Container build"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test The container
        run: echo "Testing the container"

  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "App is deployed"
